# goal
PickUp[] pickups
---
# result
bool success
int32 error_code    # 0=success, 1=waypoint failure, 2=navigation failure
string error_msg

---
# feedback
geometry_msgs/PoseStamped current_pose
float32 distance_remaining
