# Request
geometry_msgs/PoseStamped target_pose

---
# Response
bool success
int32 error_code
string error_msg

---
# Feedback
geometry_msgs/PoseStamped current_pose
builtin_interfaces/Duration navigation_time
builtin_interfaces/Duration estimated_time_remaining
int16 number_of_recoveries
float32 distance_remaining