# general_station:
"냉동":
  pose:
    x: 1.744
    y: -0.740
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.71
      w: 0.704

# "fresh_station":
"신선":
  pose:
    x: 1.744
    y: 0.398
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

# frozen_station:
"일반":
  pose:
    x: 0.992
    y: -0.061
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.705
      w: 0.708

# dropoff_station:
"목적지":
  pose:
    x: -0.405
    y: -0.737
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

# charging_station_1:
"출발지1":
  pose:
    x: -0.09
    y: 0.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

# charging_station_2:
"출발지2":
  pose:
    x: -0.06
    y: 0.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

# charging_station_3:
"출발지3":
  pose:
    x: 0.0
    y: 0.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0


"start_point21":
  pose:
    x: 0.272
    y: -0.002
    z: 0.0024
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

"start_point22":
  pose:
    x: 0.272
    y: -0.002
    z: 0.002
    orientation:
      x: -0.0
      y: 0.0
      z: -0.714
      w: 0.699

"start_point23":
  pose:
    x: 0.272
    y: -0.002
    z: 0.002
    orientation:
      x: -0.0
      y: 0.0
      z: -0.714
      w: 0.699