apple_shelf:
  pose:
    x: 0.8
    y: 1.5
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

peach_shelf:
  pose:
    x: 3.5
    y: 2.5
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 1.0
      w: 0.0

beer_shelf:
  pose:
    x: 2.0
    y: 3.5
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.707
      w: 0.707

lotion_shelf:
  pose:
    x: 4.0
    y: 1.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: -0.707
      w: 0.707

dropoff:
  pose:
    x: 5.0
    y: 5.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

charging_station_1:
  pose:
    x: 5.0
    y: 5.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

charging_station_2:
  pose:
    x: 5.0
    y: 5.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0

charging_station_3:
  pose:
    x: 5.0
    y: 5.0
    z: 0.0
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0